import img1 from "./image/img1.jpg" ;
import img2 from "./image/img2.jpg" ;
import img3 from "./image/img3.jpg" ;
import img4 from "./image/img4.png" ;

const sdata= [
    {id:1,
     img:img1,
     name: "Homemade Pizza",
     price: "$19",
     rating:"4.7",
     time:"45-50 min",
     item:0 
    },
    {id:2,
     img:img2,
     name: "Homemade Pizza",
     price: "$19",
     rating:"4.7",
     time:"45-50 min",
     item:0,
    },
    {id:3,
      img:img3,
    name: "Homemade Pizza",
     price: "$19",
     rating:"4.7",
     time:"45-50 min",
     item:0,
    },
    {id:4,
      img:img4,
    name: "Homemade Pizza",
     price: "$19",
     rating:"4.7",
     time:"45-50 min",
     item:0,
    },
    {id:5,
    img:img1,
    name: "Homemade Pizza",
    price: "$19",
    rating:"4.7",
    time:"45-50 min",
    item:0,
   },
   {id:6,
    img:img2,
   name: "Homemade Pizza",
    price: "$19",
    rating:"4.7",
    time:"45-50 min",
    item:0,
   },
   {id:7,
    img:img3,
   name: "Homemade Pizza",
    price: "$19",
    rating:"4.7",
    time:"45-50 min",
    item:0,
   },
   {id:8,
    img: img4,
   name: "Homemade Pizza",
    price: "$19",
    rating:"4.7",
    time:"45-50 min",
    item:0,
   },
   {id:9,
    img:img1,
   name: "Homemade Pizza",
   price: "$19",
   rating:"4.7",
   time:"45-50 min",
   item:0,
  },
  {id:10,
    img: img2,
  name: "Homemade Pizza",
   price: "$19",
   rating:"4.7",
   time:"45-50 min",
   item:0,
  },
  {id:11,
    img: img3,
  name: "Homemade Pizza",
   price: "$19",
   rating:"4.7",
   time:"45-50 min",
   item:0,
  },
  {id:12,
  img: img4,
  name: "Homemade Pizza",
   price: "$19",
   rating:"4.7",
   time:"45-50 min",
   item:0,
  },
]
export default sdata;