import img1 from "./image/img1.jpg" ;
import img2 from "./image/img2.jpg" ;
import img3 from "./image/img3.jpg" ;
import img4 from "./image/img4.png" ;

const sdata= [
    {img:img1,
     name: "Homemade Pizza",
     price: "$19",
     rating:"4.7",
     time:"45-50 min",
    },
    {img:img2,
    name: "Homemade Pizza",
     price: "$19",
     rating:"4.7",
     time:"45-50 min",
    },
    {img:img3,
    name: "Homemade Pizza",
     price: "$19",
     rating:"4.7",
     time:"45-50 min",
    },
    {img:img4,
    name: "Homemade Pizza",
     price: "$19",
     rating:"4.7",
     time:"45-50 min",
    },
    {img:img1,
    name: "Homemade Pizza",
    price: "$19",
    rating:"4.7",
    time:"45-50 min",
   },
   {img:img2,
   name: "Homemade Pizza",
    price: "$19",
    rating:"4.7",
    time:"45-50 min",
   },
   {img:img3,
   name: "Homemade Pizza",
    price: "$19",
    rating:"4.7",
    time:"45-50 min",
   },
   {img: img4,
   name: "Homemade Pizza",
    price: "$19",
    rating:"4.7",
    time:"45-50 min",
   },
   {img:img1,
   name: "Homemade Pizza",
   price: "$19",
   rating:"4.7",
   time:"45-50 min"
  },
  {img: img2,
  name: "Homemade Pizza",
   price: "$19",
   rating:"4.7",
   time:"45-50 min",
  },
  {img: img3,
  name: "Homemade Pizza",
   price: "$19",
   rating:"4.7",
   time:"45-50 min"
  },
  {img: img4,
  name: "Homemade Pizza",
   price: "$19",
   rating:"4.7",
   time:"45-50 min",
  },
]
export default sdata;